background=/usr/share/backgrounds/background.jpg
theme-name = Catppuccin-Macchiato-Mauve
icon-theme-name = Papirus-Dark
font-name = JetBrains Mono 11
xft-antialias = true
xft-dpi = 96
xft-hintstyle = hintfull
xft-rgba = rgb
indicators = ~spacer;~host;~spacer;~clock;~spacer;~session;~language;~a11y;~power
clock-format = %H:%M
position = 50%,center 50%,center
screensaver-timeout = 0