general {
    hide_cursor = true [cite: 287]
}

background {
    monitor = 
    path = screenshot # Toma una captura de tu escritorio actual [cite: 339, 341]
    blur_passes = 2 # Difumina el fondo [cite: 342]
}

input-field {
    monitor = 
    size = 200, 50 [cite: 375]
    outline_thickness = 3 [cite: 376]
    placeholder_text = Introduce contraseña... [cite: 385]
    dots_center = true [cite: 378]
}