general {
    hide_cursor = true
}

background {
    monitor = 
    path = screenshot # Toma una captura de tu escritorio actual
    blur_passes = 2 # Difumina el fondo
}

input-field {
    monitor = 
    size = 200, 50
    outline_thickness = 3
    placeholder_text = Introduce contraseña...
    dots_center = true
}
