# ==============================================================================
# Hyprland Main Configuration
# Arch: Modular GNU Stow Setup
# ==============================================================================

# --- [ Sources ] --------------------------------------------------------------
# Se carga todo el entorno en orden estricto
source = ~/.config/hypr/conf.d/env.conf
source = ~/.config/hypr/conf.d/monitors.conf
source = ~/.config/hypr/conf.d/execs.conf
source = ~/.config/hypr/conf.d/theme.conf
source = ~/.config/hypr/conf.d/rules.conf
source = ~/.config/hypr/conf.d/keybinds.conf