# ==============================================================================
# Execs (Autostart)
# ==============================================================================

# Demonios esenciales
exec-once = /usr/lib/polkit-kde-authentication-agent-1
exec-once = dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = systemctl --user import-environment WAYLAND_DISPLAY XDG_CURRENT_DESKTOP
exec-once = waybar
exec-once = eww daemon
exec-once = eww open monitor-sidebar
exec-once = mako 
exec-once = cliphist daemon # Historial del portapapeles
exec-once = udiskie # monta discos y unidades removibles

exec-once = hypridle

# Portapapeles
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Wallpaper daemon (Hyprpaper o Swaybg)
exec-once = swaybg -m fill -i ~/Pictures/background.jpg

# Cursor
exec-once = hyprctl setcursor Bibata-Modern-Ice 24


# Tema GTK
exec-once = gsettings set org.gnome.desktop.interface gtk-theme "Catppuccin-Macchiato-Mauve"
exec-once = gsettings set org.gnome.desktop.interface icon-theme "Papirus-Dark"
exec-once = gsettings set org.gnome.desktop.interface font-name "JetBrains Mono 10"