# ==============================================================================
# Execs (Autostart)
# ==============================================================================

# Demonios esenciales
exec-once = /usr/lib/polkit-kde-authentication-agent-1 & # Ajusta a polkit-gnome si usas ese
exec-once = waybar
exec-once = eww daemon
exec-once = dunst # O reemplazable por swaync/mako

# Portapapeles
exec-once = wl-paste --type text --watch cliphist store
exec-once = wl-paste --type image --watch cliphist store

# Wallpaper daemon (Hyprpaper o Swaybg)
# exec-once = hyprpaper
