# ==============================================================================
# Atajos y Funciones (Keybinds)
# ==============================================================================

# Variables generales
$mainMod = SUPER
$terminal = kitty
$fileManager = thunar
$menu = wofi
$browser = brave-browser

# --- [ Lanzadores Básicos ] ---
bind = $mainMod, t, exec, $terminal
bind = $mainMod, d, exec, $menu --show drun
bind = $mainMod, w, exec, $browser
bind = $mainMod, c, killactive,
bind = $mainMod SHIFT, q, exit,
bind = $mainMod, v, togglefloating,
bind = $mainMod, e, exec, $fileManager
bind = $mainMod, m, exec,  $terminal --class ncmpcpp -e cava &

# --- [ Dashboard y Controles ] ---
# (Fase 3: Acá abrimos EWW)
bind = $mainMod, q, exec, eww open --toggle dashboard
bind = $mainMod, p, pseudo, # dwindle
# bind = $mainMod, j, togglesplit, # dwindle

# --- [ Enfoque de Ventanas ] ---
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# --- [ Workspaces ] ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5
bind = $mainMod, 6, workspace, 6

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5
bind = $mainMod SHIFT, 6, movetoworkspace, 6


# --- [ Control de Medios ] ---
bindl = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindl = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = , XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = , XF86MonBrightnessDown, exec, brightnessctl s 10%-
# bind = , XF86PowerOff, exec, hyprctl dispatch dpms off
bind = , XF86PowerOff, exec, hyprlock

# --- [ Control de Screenshots ] ---
#bind = , PRINT, exec, grim $(xdg-user-dir PICTURES)/$(date +'%s_screenshot.png')
#bind = $mainMod, s, exec, grim -g \"$(slurp)\" $(xdg-user-dir PICTURES)/$(date +'%s_area.png')

# Captura de pantalla completa: guarda en archivo y copia al portapapeles
bind = , PRINT, exec, grim - | wl-copy && grim $(xdg-user-dir PICTURES)/screenshots/$(date +'%s_screenshot.png')
# Captura de área seleccionada: guarda en archivo y copia al portapapeles
bind = $mainMod, s, exec, grim -g "$(slurp)" - | wl-copy && grim -g "$(slurp)" $(xdg-user-dir PICTURES)/screenshots/$(date +'%s_area.png')

# Historial del portapapeles visual (Estilo Win + V)
bind = $mainMod SHIFT, v, exec, cliphist list | wofi --dmenu | cliphist decode | wl-copy

# movimientos de ventanas
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

# redimencion con telcado

bind = $mainMod, R, submap, resize
submap = resize

binde = , right, resizeactive, 10 0
binde = , left, resizeactive, -10 0
binde = , up, resizeactive, 0 -10
binde = , down, resizeactive, 0 10

bind = , escape, submap, reset
submap = reset