# ==============================================================================
# Atajos y Funciones (Keybinds)
# ==============================================================================

$mainMod = SUPER

# --- [ Lanzadores Básicos ] ---
bind = $mainMod, T, exec, kitty
bind = $mainMod, D, exec, wofi --show drun
bind = $mainMod, C, killactive,
bind = $mainMod SHIFT, Q, exit,
bind = $mainMod, V, togglefloating,

# --- [ Dashboard y Controles ] ---
# (Fase 3: Acá abrimos EWW)
bind = $mainMod, W, exec, eww open --toggle dashboard
bind = $mainMod, P, pseudo, # dwindle
bind = $mainMod, J, togglesplit, # dwindle

# --- [ Enfoque de Ventanas ] ---
bind = $mainMod, left, movefocus, l
bind = $mainMod, right, movefocus, r
bind = $mainMod, up, movefocus, u
bind = $mainMod, down, movefocus, d

# --- [ Workspaces ] ---
bind = $mainMod, 1, workspace, 1
bind = $mainMod, 2, workspace, 2
bind = $mainMod, 3, workspace, 3
bind = $mainMod, 4, workspace, 4
bind = $mainMod, 5, workspace, 5

bind = $mainMod SHIFT, 1, movetoworkspace, 1
bind = $mainMod SHIFT, 2, movetoworkspace, 2
bind = $mainMod SHIFT, 3, movetoworkspace, 3
bind = $mainMod SHIFT, 4, movetoworkspace, 4
bind = $mainMod SHIFT, 5, movetoworkspace, 5

# --- [ Control de Medios ] ---
bindl = , XF86AudioRaiseVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%+
bindl = , XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindl = , XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindl = , XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle
bindel = ,XF86MonBrightnessUp, exec, brightnessctl s 10%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl s 10%-   ll

# --- [ Control de Screenshots ] ---
bind = , PRINT, exec, grim $(xdg-user-dir PICTURES)/$(date +'%s_screenshot.png')
bind = $mainMod, s, exec, grim -g \"$(slurp)\" $(xdg-user-dir PICTURES)/$(date +'%s_area.png')
