# ==============================================================================
# Monitores e Inputs
# ==============================================================================

# Detección automática (reemplazar si usas multi-monitor con posiciones fijas)
monitor=,preferred,auto,1

# Input general
input {
    kb_layout = us,es
    kb_variant =
    kb_model =
    kb_options = grp:win_space_toggle
    kb_rules =
    follow_mouse = 1

    touchpad {
        natural_scroll = yes
        tap-to-click = yes
    }

    sensitivity = 0 # -1.0 a 1.0
}
# Gestures
gestures {
    gesture = 3, horizontal, workspace
}