# ==============================================================================
# Rules & Blur (Window & Layer rules)
# ==============================================================================

# ====================
# Layer Rules (Barras, Menus)
# ====================

layerrule = blur, waybar
layerrule = ignorezero, waybar

layerrule = blur, eww-dashboard
layerrule = ignorealpha 0.5, eww-dashboard

layerrule = blur, wofi
layerrule = ignorezero, wofi

# ====================
# Window Rules (Apps flotantes o ignoradas)
# ====================

windowrulev2 = float, class:(pavucontrol)
windowrulev2 = float, class:(blueman-manager)
windowrulev2 = float, class:(nm-connection-editor)

windowrulev2 = opacity 0.95 0.95, class:(kitty)

windowrulev2 = idleinhibit fullscreen, class:(firefox)
