# ==============================================================================
# Theme, Animations & Glassmorphism
# Paleta base: Catppuccin Macchiato
# ==============================================================================

general {
    gaps_in = 5
    gaps_out = 10
    border_size = 2
    col.active_border = rgb(c6a0f6) rgb(8aadf4) 45deg
    col.inactive_border = rgb(6e738d)
    layout = dwindle
}

decoration {
    rounding = 12
    
    blur {
        enabled = true
        size = 8
        passes = 3
    }
    
    shadow {
        enabled = true
        range = 15
        render_power = 3
        color = rgba(11111b99)
    }
}

animations {
    enabled = yes

    bezier = easeOutQuint,   0.23, 1,    0.32, 1
    bezier = easeInOutCubic, 0.65, 0.05, 0.36, 1
    bezier = linear,         0,    0,    1,    1
    bezier = almostLinear,   0.5,  0.5,  0.75, 1
    bezier = quick,          0.15, 0,    0.1,  1

    animation = border, 1, 5.39, easeOutQuint
    animation = windows, 1, 4.79, easeOutQuint
    animation = windowsIn, 1, 4.1, easeOutQuint, popin 87%
    animation = windowsOut, 1, 1.49, linear, popin 87%
    animation = fade, 1, 3.03, linear
    animation = workspaces, 1, 4, easeOutQuint, slide
}